import React, { useState, useEffect } from 'react';
import { ArrowLeft, Save, Upload } from 'lucide-react';
import { Breadcrumb } from '../../components/Breadcrumb';
import { ResponsivePageHeader } from '../../components/responsive/ResponsiveFilters';
import { useAppDispatch, useAppSelector } from '../../store/hooks';
import { fetchVendors } from '../../store/slices/vendorSlice';
import { fetchPurchaseOrders } from '../../store/slices/purchaseOrderSlice';
import { createInvoice } from '../../store/slices/invoiceSlice';
import { toast } from 'sonner';

interface InvoiceFormProps {
  invoiceId?: string;
  isEdit?: boolean;
}

export function InvoiceForm({ invoiceId, isEdit = false }: InvoiceFormProps) {
  const dispatch = useAppDispatch();
  const { vendors } = useAppSelector((state) => state.vendors);
  const { purchaseOrders } = useAppSelector((state) => state.purchaseOrders);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    vendorId: '',
    poId: '',
    poReference: '',
    invoiceNumber: '',
    amount: '',
    invoiceDate: '',
    document: null as File | null,
  });

  useEffect(() => {
    dispatch(fetchVendors({ limit: 100 }));
    dispatch(fetchPurchaseOrders({ limit: 100 }));
  }, [dispatch]);

  const navigateTo = (path: string) => {
    const event = new CustomEvent('navigate', { detail: { path } });
    window.dispatchEvent(event);
  };

  const handlePOChange = (poCode: string) => {
    const selectedPO = purchaseOrders.find(po => po.poCode === poCode);
    if (selectedPO) {
      setFormData(prev => ({
        ...prev,
        poReference: poCode,
        poId: selectedPO.id,
        vendorId: selectedPO.vendorId,
        amount: selectedPO.totalAmount.toString()
      }));
    } else {
      setFormData(prev => ({ ...prev, poReference: poCode }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      setIsSubmitting(true);
      const payload = {
        vendorId: formData.vendorId,
        poId: formData.poId,
        poReference: formData.poReference,
        invoiceDate: formData.invoiceDate,
        amount: Number(formData.amount),
        // invoiceNumber is currently auto-generated by backend
      };

      const resultAction = await dispatch(createInvoice(payload));
      
      if (createInvoice.fulfilled.match(resultAction)) {
        toast.success('Invoice created successfully!');
        navigateTo('/supply-chain/invoices');
      } else {
        toast.error('Failed to create invoice');
      }
    } catch (error) {
      toast.error('An unexpected error occurred');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F7F7F7]">
      <Breadcrumb
        items={[
          { label: 'Supply Chain Management', path: '/supply-chain/vendors' },
          { label: 'Invoices', path: '/supply-chain/invoices' },
          { label: isEdit ? 'Edit Invoice' : 'Add Invoice' },
        ]}
      />

      <ResponsivePageHeader title={isEdit ? 'Edit Invoice' : 'Add Invoice'} />

      <div className="p-6">
        <div className="max-w-4xl mx-auto">
          <button
            onClick={() => navigateTo('/supply-chain/invoices')}
            className="mb-6 flex items-center gap-2 text-[#0A6659] hover:underline"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Invoices
          </button>

          <form onSubmit={handleSubmit} className="bg-white rounded-xl border border-[#262C3633] p-6 space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-[#262C36] mb-4">Invoice Information</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    PO Reference <span className="text-[#F56565]">*</span>
                  </label>
                  <select
                    required
                    value={formData.poReference}
                    onChange={(e) => handlePOChange(e.target.value)}
                    className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl bg-white"
                  >
                    <option value="">Select PO</option>
                    {purchaseOrders?.map(po => (
                      <option key={po.id} value={po.poCode}>{po.poCode} ({po.vendor?.vendorName})</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    Vendor <span className="text-[#F56565]">*</span>
                  </label>
                  <select
                    required
                    value={formData.vendorId}
                    onChange={(e) => setFormData({ ...formData, vendorId: e.target.value })}
                    className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl bg-white"
                  >
                    <option value="">Select vendor</option>
                    {vendors?.map(vendor => (
                      <option key={vendor.id} value={vendor.id}>{vendor.vendorName}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    Invoice Number <span className="text-[#F56565]">*</span>
                  </label>
                  <input
                    type="text"
                    required
                    value={formData.invoiceNumber}
                    onChange={(e) => setFormData({ ...formData, invoiceNumber: e.target.value })}
                    className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl bg-white"
                    placeholder="INV-XXXX"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    Amount <span className="text-[#F56565]">*</span>
                  </label>
                  <input
                    type="number"
                    required
                    value={formData.amount}
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                    className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl bg-white"
                    placeholder="0.00"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    Invoice Date <span className="text-[#F56565]">*</span>
                  </label>
                  <input
                    type="date"
                    required
                    value={formData.invoiceDate}
                    onChange={(e) => setFormData({ ...formData, invoiceDate: e.target.value })}
                    className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl bg-white"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[#262C36] mb-2">
                    Upload Invoice Document
                  </label>
                  <label className="w-full h-[44px] px-4 border border-[#262C3633] rounded-xl flex items-center gap-2 cursor-pointer hover:bg-[#F7F7F7] bg-white">
                    <Upload className="w-4 h-4 text-[#718096]" />
                    <span className="text-sm text-[#718096]">
                      {formData.document ? formData.document.name : 'Choose file'}
                    </span>
                    <input
                      type="file"
                      accept=".pdf,.jpg,.png"
                      onChange={(e) => setFormData({ ...formData, document: e.target.files?.[0] || null })}
                      className="hidden"
                    />
                  </label>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-3 pt-4 border-t border-[#E5E7EB]">
              <button
                type="button"
                onClick={() => navigateTo('/supply-chain/invoices')}
                className="h-[44px] px-6 border border-[#262C3633] text-[#262C36] rounded-xl hover:bg-[#F7F7F7]"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="h-[44px] px-6 bg-[#0A6659] text-white rounded-xl hover:bg-[#0A6659]/90 flex items-center gap-2 disabled:opacity-50"
              >
                {isSubmitting ? (
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                ) : (
                  <Save className="w-5 h-5" />
                )}
                {isEdit ? 'Update Invoice' : 'Save Invoice'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
